spring:
  application:
    name: info-service
  datasource:
    url: jdbc:postgresql://localhost:5432/info-service
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yml
  cache:
    type: redis
  data:
    redis:
      host: localhost
      password: password
      port: 6379

springdoc:
  api-docs:
    path: '/api-docs'
  swagger-ui:
    groups-order: DESC
    path: '/swagger-ui'
    operationsSorter: method
  default-consumes-media-type: 'application/json'
  default-produces-media-type: 'application/json'
  model-converters:
    pageable-converter:
      enabled: true

exchange-rate:
  url: 'https://api.apilayer.com/exchangerates_data/latest?symbols=USD,CHF,EUR,JPY,GBP,AUD,CNY,DKK&base=PLN'
  apikey: 'wiQKT18tF6xkpFt7IvQ5mmboz0tnpjh5'
  sale-percent: '1.1'

schedule:
  cron:
    updateExchangeRates: "0 31 13 * * *"